//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace protocol.rabbitmq.test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("protocol.rabbitmq.test.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;NumProtocol&quot;:&quot;ae8202c7-5155-47af-a10e-9322a471f701&quot;,&quot;NumViaDocumento&quot;:1,&quot;CPF&quot;:&quot;82792089334&quot;,&quot;RG&quot;:&quot;123456&quot;,&quot;Nome&quot;:&quot;NEY DIXON SANTIAGO MARINHO&quot;,&quot;NomeMae&quot;:&quot;JOSELY RIBEIRO SANTIAGO&quot;,&quot;NomePai&quot;:&quot;LUIS SANTOS MARINHO&quot;,&quot;Foto&quot;:null},{&quot;NumProtocol&quot;:&quot;0f8d0215-0b79-485c-9659-b6e760438723&quot;,&quot;NumViaDocumento&quot;:1,&quot;CPF&quot;:&quot;82792089334&quot;,&quot;RG&quot;:&quot;123456&quot;,&quot;Nome&quot;:&quot;NEY DIXON SANTIAGO MARINHO&quot;,&quot;NomeMae&quot;:&quot;JOSELY RIBEIRO SANTIAGO&quot;,&quot;NomePai&quot;:&quot;LUIS SANTOS MARINHO&quot;,&quot;Foto&quot;:null},{&quot;NumProtocol&quot;:&quot;05825860-092d-424e-8bff-8d278fcd8c97&quot;,&quot;NumVia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json_1 {
            get {
                return ResourceManager.GetString("json_1", resourceCulture);
            }
        }
    }
}
